"""change column role[str] > is_admin[bool]

Revision ID: 7fb4110fe7e3
Revises: 124ef4ea3c66
Create Date: 2024-11-21 11:29:07.160651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb4110fe7e3'
down_revision = '124ef4ea3c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
